### ISSUE TITLE
Sample actions

### ISSUE THREAD

**Issue by Ivan-Kalatchev** [SKYWARE-Group/EventsModel#2]
### Discussed in https://github.com/SKYWARE-Group/EventsModel/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **Ivan-Kalatchev** September 30, 2023</sup>
The event model should be extended as to support describing sample actions such as `creation`, `barcode generation` and `deletion`.</div>

**Comment by kalatchev** [comment]
Done.
